weights: /home/hranjb/data/ST-TR/experiments/exp_sttr/epoch51_model.pt
# feeder
feeder: st_gcn.feeder.Feeder_islr
train_feeder_args:
  random_choose: False
  random_move: False
  window_size: 112
  data_path: /home/hranjb/data/islr101_train.npy
  label_path: /home/hranjb/data/islr101_train_label.npy
  name_path: /home/hranjb/data/islr101_train_name.npy
test_feeder_args:
  data_path: /home/hranjb/data/islr101_test.npy
  label_path: /home/hranjb/data/islr101_test_label.npy
  name_path: /home/hranjb/data/islr101_test_name.npy

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 101
  channel: 3
  window_size: 112
  num_person: 1
  num_point: 67
  dropout: 0
  graph: st_gcn.graph.Islr
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True
  attention: True
  only_attention: True
  tcn_attention: True
  data_normalization: True
  skip_conn: True
  weight_matrix: 2
  only_temporal_attention: True
  bn_flag: True
  attention_3: False
  kernel_temporal: 9
  more_channels: False
  double_channel: False
  drop_connect: True
  concat_original: True
  all_layers: False
  adjacency: False
  agcn: False
  dv: 0.25
  dk: 0.25
  Nh: 8
  n: 4
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  relative: False
  visualization: False

  #optical_flow: True

#optim
scheduler: 1
weight_decay: 0.0001
base_lr: 0.001
step: [45, 55]

# training
device: [0]
batch_size: 32
test_batch_size: 8
num_epoch: 120
nesterov: True
